version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: vamsi  # Adjust the password as needed
      MYSQL_DATABASE: myapp_development            # Adjust the database name as needed
      MYSQL_USER: vamsi                    # Adjust the username as needed
      MYSQL_PASSWORD: vamsi      # Adjust the user's password as needed
    ports:
      - "3026:3306"   # Expose MySQL port 3306 inside the container to port 3026 on the host
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  mysql_data:
    driver: local

networks:
  mysql_network:
    driver: bridge
