default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: myapp_development
  username: root
  password: vamsi
  port: 3026
  host: 127.0.0.1

test:
  <<: *default
  database: myapp_test
  username: root
  password: vamsi
  port: 3026
  host: 127.0.0.1

production:
  <<: *default
  database: myapp_production
  username: root
  password: vamsi
  host: 127.0.0.1
  pool: 15
  timeout: 5000
